#if UNITY_EDITOR
using System;
using System.Collections.Generic;
using UnityEditor;

namespace AvatarSmartBackup.Localization
{
    [InitializeOnLoad]
    static class LocalizationData
    {
        static LocalizationData()
        {
            var en = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                {"dlg.log.notfound", "Log folder not found."},
                {"dlg.log.title", "Log Folder"},
                {"rp.asset.types", ".asset types"},
                {"rp.backup.failed.body", "Pre-restore backup failed. Continue restore anyway?"},
                {"rp.backup.failed.title", "Backup failed"},
                {"rp.cancel", "Cancel"},
                {"rp.current", "Current"},
                {"rp.current.notfound", "No Current/ backup found."},
                {"rp.deselect.all", "Deselect All"},
                {"rp.filter.changed", "Changed"},
                {"rp.filter.changed.tt", "Show Changed"},
                {"rp.filter.hideMeta", "Hide .meta"},
                {"rp.filter.hideMeta.tt", "Hide .meta"},
                {"rp.filter.new", "New"},
                {"rp.filter.new.tt", "Show New"},
                {"rp.filter.same", "Same"},
                {"rp.filter.same.tt", "Show Same"},
                {"rp.filter.namesOnly", "Names only"},
                {"rp.filter.namesOnly.tt", "Display only file names"},
                {"rp.filter.highlight", "Highlight"},
                {"rp.filter.highlight.tt", "Highlight search matches"},
                {"rp.fold.filters", "Filters"},
                {"rp.fold.selection", "Selection"},
                {"rp.fold.summary", "Summary"},
                {"rp.easy.banner", "Easy mode hides advanced filters. Switch to Advanced for full control when you need it."},
                {"rp.easy.banner.hide", "Hide tip"},
                {"rp.easy.filters.note", "Quick filter only. Advanced toggles live in Advanced mode."},
                {"rp.easy.selection.note", "Quick actions shown. Advanced batch tools are available in Advanced mode."},
                {"rp.help", "Pick the files you need. Summary, filters and selections sit below. The safety backup toggle is at the bottom."},
                {"rp.help.easy", "Pick the files you need. Summary, quick filters and the file list are below. The safety backup toggle stays at the bottom."},
                {"rp.info.changes", "Recorded changes: {0} (removed: {1})."},
                {"rp.info.full", "Full checkpoint: files are ready for direct restore."},
                {"rp.info.incr", "Incremental version: automatically reconstructed from checkpoint #{0}."},
                {"rp.invert", "Invert"},
                {"rp.items.selected", "Items: {0}    Selected: {1}"},
                {"rp.no", "No"},
                {"rp.no.files", "No files match the current filters."},
                {"rp.open.folder", "Open Folder"},
                {"rp.open.folder.tt", "Open version folder"},
                {"rp.refresh", "Refresh"},
                {"rp.reset", "Reset"},
                {"rp.restore.all", "Restore ALL"},
                {"rp.restore.all.tt", "Restore all files"},
                {"rp.restore.done", "Restore completed. Files restored: {0}"},
                {"rp.restore.copy.done", "Files copied: {0}\nDestination: {1}"},
                {"rp.restore.incomplete", "Backup in progress or not complete."},
                {"rp.restore.notfound", "Version #{0} not found."},
                {"rp.restore.prepare.fail", "Failed to prepare snapshot for version {0}:\n{1}"},
                {"rp.restore.prepareVersion.fail", "Failed to prepare version data:\n{0}"},
                {"rp.restore.copy.select", "Choose destination folder"},
                {"rp.restore.selected", "Restore Selected"},
                {"rp.restore.selected.tt", "Restore selected files"},
                {"rp.restore.copy", "Restore as Copy"},
                {"rp.restore.copy.tt", "Copy selected files to another folder"},
                {"rp.restore.title", "Restore"},
                {"rp.safety", "Safety Backup"},
                {"rp.mode.choice.advanced", "Advanced mode is active. Full controls are now available."},
                {"rp.mode.choice.easy", "Easy mode is active. You can switch later from the Backup window."},
                {"rp.mode.choice.title", "Mode updated"},
                {"rp.mode.gate.body", "Choose how you want to restore files before continuing."},
                {"rp.mode.switch.body", "Advanced mode unlocks all filters and batch tools. Continue?"},
                {"rp.mode.switch.title", "Switch to Advanced"},
                {"rp.safety.tt", "Make a safety copy before restoring"},
                {"rp.scan.bar", "Building diff"},
                {"rp.scan.progress", "Scanning files... {0}/{1} ({2:0.0}%)"},
                {"rp.search", "Search:"},
                {"rp.select.all", "Select All"},
                {"rp.select.newchanged", "Select New+Changed"},
                {"rp.selected.summary", "Selected: {0} files ({1})"},
                {"rp.stat.changed", "CHANGED"},
                {"rp.stat.new", "NEW"},
                {"rp.stat.same", "SAME"},
                {"rp.stats", "Files: {0}   New: {1}   Changed: {2}   Same: {3}"},
                {"rp.title", "Restore Preview"},
                {"rp.top.extensions", "Top extensions"},
                {"rp.version.notfound", "Version files not found."},
                {"rp.yes", "Yes"},
                {"tt.advanced.openLogFolder", "Open the logs folder for support"},
                {"tt.advanced.refreshVersions", "Reload the list of versions"},
                {"tt.backup.now.advanced", "Run a backup now (no cooldown in Advanced Mode)"},
                {"tt.latest.none", "No version available"},
                {"tt.latest.open", "Open the latest version to restore or inspect"},
                {"tt.open.backup.folder", "Open the backups folder"},
                {"tt.overview.gotoVersions", "Open Versions tab"},
                {"tt.versions.refresh", "Reload versions from disk"},
                {"ui.advanced.openLogFolder", "Open Log Folder"},
                {"ui.advanced.refreshVersions", "Refresh Versions"},
                {"ui.advanced.tools.title", "Advanced Tools"},
                {"ui.advancedMode", "Advanced Mode"},
                {"ui.advancedMode.tooltip", "Show advanced options (filters, performance, verify, retention)."},
                {"ui.autobackups.last", "Last"},
                {"ui.autobackups.next", "Next"},
                {"ui.autobackups.off", "Automatic Backups: OFF"},
                {"ui.autobackups.on", "Automatic Backups: ON"},
                {"ui.autobackups.title", "Automatic Backups"},
                {"ui.filters.pending", "Filter changes pending. The next backup will create a full checkpoint to apply the new scope."},
                {"ui.mode.label", "Mode"},
                {"ui.mode.easy", "Easy"},
                {"ui.mode.advanced", "Advanced"},
                {"ui.easy.summary", "Easy mode shows the essentials. Switch to Advanced for detailed controls."},
                                {"ui.easy.switch", "Switch to Advanced"},
                {"onboarding.title", "Welcome to Avatar Smart Backup"},
                {"onboarding.body", "Choose the experience that fits you best. You can change it later from the mode selector."},
                {"onboarding.learn", "Learn more"},
                {"onboarding.learn.body", "Easy mode keeps the essentials. Advanced mode exposes all tools."},
                {"ui.autobackups.toggle.tt", "Toggle background backup scheduler"},
                {"ui.backup.now", "Backup Now"},
                {"ui.interval.label", "Interval"},
                {"ui.interval.min", "min"},
                {"ui.interval.sec", "sec"},
                {"ui.latest.previewRestore", "Preview & Restore latest"},
                {"ui.never", "never"},
                {"ui.open.backup.folder", "Open Backup Folder"},
                {"ui.overview.created", "Created:"},
                {"ui.overview.filesSize", "Files"},
                {"ui.overview.gotoVersions", "Go to Versions"},
                {"ui.overview.latest.label", "Latest Version:"},
                {"ui.overview.latest.title", "Latest Version"},
                {"ui.overview.noDescription", "(no description)"},
                {"ui.overview.none", "No versions available"},
                {"ui.overview.size", "Size"},
                {"ui.tabs.backup", "Backup"},
                {"ui.tabs.versions", "Versions"},
                {"ui.versions.help", "Restore points are automatically created when there are changes. Use the star to pin, click to select, double-click to preview."},
                {"ui.versions.refresh", "Refresh"},
                {"ui.versions.previewRestore", "Preview & Restore"},
                {"ui.versions.title", "Versions"},
                {"vh.created", "Created:"},
                {"vh.desc", "Description: {0}"},
                {"vh.folder.notfound.body", "The version folder could not be found."},
                {"vh.folder.notfound.title", "Folder Not Found"},
                {"vh.latest", "Latest"},
                {"vh.load.error", "Error loading versions: {0}"},
                {"vh.loading", "Loading versions..."},
                {"vh.none", "No versions found. Versions are automatically created after each backup with changes."},
                {"vh.open.folder", "Open Folder"},
                {"vh.show.changes", "Show Changes"},
                {"vh.refresh", "Refresh"},
                {"vh.restore", "Restore to This Version"},
                {"vh.restore.confirm.body", "Are you sure you want to restore to version #{0}?\n\nDescription: {1}\nCreated: {2}\n\nThis will replace your current Assets with the backup from this version."},
                {"vh.restore.confirm.cancel", "Cancel"},
                {"vh.restore.confirm.ok", "Restore"},
                {"vh.restore.confirm.title", "Confirm Restore"},
                {"vh.restore.failed.body", "Failed to restore version: {0}"},
                {"vh.restore.failed.title", "Restore Failed"},
                {"vh.restore.location.body", "The backup files for version #{0} are located at:\n\n{1}\n\nYou can manually copy the files back to your Assets folder if needed."},
                {"vh.restore.location.title", "Restore Location"},
                {"vh.restore.notfound.body", "The backup folder for version #{0} could not be found at:\n\n{1}"},
                {"vh.restore.notfound.title", "Backup Not Found"},
                {"vh.tip.cleanup", "Tip: Versions are automatically cleaned up to keep only the 10 most recent ones."},
                {"vh.title", "Backup Versions"},
                {"vh.total", "Total Versions: {0}"},
                {"vh.version.header", "Version #{0}"},
                {"vc.window.title", "Changes for v{0}"},
                {"vc.error.title", "Show changes"},
                {"vc.error.body", "Unable to read changes:\n{0}"},
                {"vc.error.noversion", "Unable to open changes window: no version data."},
                {"vc.no.version", "No version data available."},
                {"vc.version.header", "Version #{0}"},
                {"vc.summary.checkpoint", "Full checkpoint (complete snapshot)."},
                {"vc.summary.incremental", "Incremental version (based on checkpoint #{0})."},
                {"vc.summary.changed", "Changed: {0}"},
                {"vc.summary.removed", "Removed: {0}"},
                {"vc.summary.bytes.changed", "Delta: {0}"},
                {"vc.summary.bytes.removed", "Removed bytes: {0}"},
                {"vc.filter.search", "Search"},
                {"vc.filter.added", "New"},
                {"vc.filter.modified", "Changed"},
                {"vc.filter.removed", "Removed"},
                {"vc.filter.clear", "Clear"},
                {"vc.filter.namesonly", "File name only"},
                {"vc.filter.highlight", "Highlight hits"},
                {"vc.none", "No recorded changes for this version."},
                {"vc.none.filters", "Filters hide all entries. Adjust the toggles or search."},
                {"vc.kind.added", "Added"},
                {"vc.kind.modified", "Modified"},
                {"vc.kind.removed", "Removed"},
                {"vc.badge.checkpoint", "Checkpoint"},
                {"vc.badge.incremental", "Incremental"},
                {"warn.backup.speed", "At {0} MB/s, backing up {1:0.0} MB takes ~{2:0.0} min, exceeding the interval."},
                {"window.main.autobackup.help", "Automatic safety copies run in the background. Use 'Backup Now' to force one (throttled)."},
                {"window.main.header", "Avatar Smart Backup"},
                {"window.main.title", "Avatar Smart Backup"},
                {"window.version.history.help", "Versions are of two types: full checkpoints and incremental. Incremental versions store only changes since the previous checkpoint."},
            {"ui.advanced.settings", "Advanced Settings"},
            {"ui.versioning.policy.title", "Versioning policy"},
            {"ui.versioning.policy.option.balanced", "Automatic"},
            {"ui.versioning.policy.option.frequent", "Frequent"},
            {"ui.versioning.policy.option.manual", "Manual"},
            {"ui.versioning.policy.mode", "Preset"},
            {"ui.versioning.policy.mode.tooltip", "Choose how often checkpoints are forced."},
            {"ui.versioning.policy.balanced.help", "Automatic checkpoints based on project activity."},
            {"ui.versioning.policy.frequent.help", "Favors frequent checkpoints after significant changes."},
            {"ui.versioning.policy.manual.label", "Checkpoint every (incremental versions)"},
            {"ui.versioning.policy.manual.tooltip", "Number of incremental versions before forcing a full checkpoint."},
            {"ui.versioning.policy.manual.help", "Forces a full checkpoint after {0} incremental versions."},
            {"ui.performance.title", "Performance"},
            {"ui.performance.autoThrottle", "Auto throttle (recommended)"},
            {"ui.performance.autoThrottle.tt", "Automatically cap disk throughput to keep the editor responsive."},
            {"ui.performance.threads", "Max parallel threads"},
            {"ui.performance.threads.tt", "Concurrent worker threads for hashing and copying."},
            {"ui.performance.saveScenes", "Save open scenes before backup"},
            {"ui.performance.saveScenes.tt", "Save dirty scenes before running a backup."},
            {"ui.performance.autothrottle.off", "Auto throttle is disabled. Manual speed caps will be used if set."},
            {"ui.debug.tools.title", "Debug tools"},
            {"ui.debug.tools.enable", "Enable debug tools"},
            {"ui.debug.tools.enable.tt", "Turn on diagnostics and manual overrides."},
            {"ui.debug.tools.global", "Use global settings"},
            {"ui.debug.tools.global.tt", "Share this configuration across projects."},
            {"ui.debug.tools.throughput", "Measured throughput: {0:0.0} MB/s"},
            {"ui.debug.tools.throughput.none", "Benchmark has not been run yet."},
            {"ui.debug.tools.benchmark", "Run benchmark again"},
            {"ui.debug.tools.benchmark.busy", "Benchmark unavailable while a backup is running."},
            {"ui.debug.tools.cooldowns", "Manual cooldowns"},
            {"ui.debug.tools.snapshot.cooldown", "Snapshot cooldown (s)"},
            {"ui.debug.tools.snapshot.cooldown.tt", "Minimum seconds between manual snapshots."},
            {"ui.debug.tools.benchmark.cooldown", "Benchmark cooldown (s)"},
            {"ui.debug.tools.benchmark.cooldown.tt", "Minimum seconds between manual benchmark runs."},
            {"ui.debug.tools.backup.cooldown", "Min backup interval (s)"},
            {"ui.debug.tools.backup.cooldown.tt", "Minimum seconds between manual backup requests."},
            {"ui.debug.tools.logs", "Detailed file logging"},
            {"ui.debug.tools.logs.tt", "Write verbose file logs for troubleshooting."},
            {"ui.debug.tools.snapshots.info", "Zip snapshots are managed automatically. Legacy settings remain available for compatibility."},
            {"ui.debug.tools.disabled", "Enable to access diagnostics and manual overrides."},
            {"ui.versions.latestBadge", "Latest"},
            {"ui.versions.status.writing", "(writing...)"},
            };

            var it = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
            {
                {"dlg.log.notfound", "Cartella dei log non trovata."},
                {"dlg.log.title", "Cartella dei log"},
                {"rp.asset.types", "Tipi di asset"},
                {"rp.easy.banner", "La Modalità Semplice nasconde i filtri avanzati. Passa ad Avanzata quando ti serve il pieno controllo."},
                {"rp.easy.banner.hide", "Nascondi suggerimento"},
                {"rp.easy.filters.note", "Filtro rapido. I controlli avanzati sono in Modalità Avanzata."},
                {"rp.easy.selection.note", "Azioni rapide disponibili. Gli strumenti avanzati sono in Modalità Avanzata."},
                {"rp.help", "Scegli cosa ripristinare. Riepilogo, filtri e selezioni sono qui sotto. Il backup di sicurezza è in fondo."},
                {"rp.help.easy", "Scegli i file di cui hai bisogno. Riepilogo, filtri rapidi e lista file sono qui sotto. Il backup di sicurezza resta in fondo."},
                {"rp.mode.choice.advanced", "Modalit Avanzata attiva. Hai ora tutti i controlli disponibili."},
                {"rp.mode.choice.easy", "Modalit Semplice attiva. Puoi cambiare in seguito dalla finestra Backup."},
                {"rp.mode.choice.title", "Modalit aggiornata"},
                {"rp.mode.gate.body", "Scegli come vuoi ripristinare i file prima di continuare."},
                {"rp.mode.switch.body", "La Modalit Avanzata sblocca tutti i filtri e gli strumenti batch. Vuoi continuare?"},
                {"rp.mode.switch.title", "Passa ad Avanzata"},
                {"rp.safety.tt", "Crea una copia di sicurezza prima del ripristino"},
                {"rp.cancel", "Annulla"},
                {"rp.current", "Attuale"},
                {"rp.current.notfound", "Nessun backup Current/ trovato."},
                {"rp.deselect.all", "Deseleziona tutto"},
                {"rp.filter.changed", "Modificati"},
                {"rp.filter.changed.tt", "Mostra modificati"},
                {"rp.filter.hideMeta", "Nascondi .meta"},
                {"rp.filter.hideMeta.tt", "Nascondi i file .meta"},
                {"rp.filter.new", "Nuovi"},
                {"rp.filter.new.tt", "Mostra nuovi"},
                {"rp.filter.same", "Uguali"},
                {"rp.filter.same.tt", "Mostra uguali"},
                {"rp.filter.namesOnly", "Solo nomi"},
                {"rp.filter.namesOnly.tt", "Visualizza solo i nomi dei file"},
                {"rp.filter.highlight", "Evidenzia"},
                {"rp.filter.highlight.tt", "Evidenzia i risultati della ricerca"},
                {"rp.fold.filters", "Filtri"},
                {"rp.fold.selection", "Selezione"},
                {"rp.fold.summary", "Riepilogo"},
                {"rp.help", "Scegli cosa ripristinare. Espandi le sezioni: Riepilogo, Filtri, Selezione, File. L'opzione per il backup di sicurezza Ã¨ nel footer."},
                {"rp.info.changes", "Modifiche registrate: {0} (rimossi: {1})."},
                {"rp.info.full", "Checkpoint completo: i file sono pronti per il ripristino diretto."},
                {"rp.info.incr", "Versione incrementale: ricostruita automaticamente dal checkpoint #{0}."},
                {"rp.invert", "Inverti"},
                {"rp.items.selected", "Elementi: {0}    Selezionati: {1}"},
                {"rp.no", "No"},
                {"rp.no.files", "Nessun file corrisponde ai filtri attuali."},
                {"rp.open.folder", "Apri cartella"},
                {"rp.open.folder.tt", "Apri la cartella della versione"},
                {"rp.refresh", "Aggiorna"},
                {"rp.reset", "Reimposta"},
                {"rp.restore.all", "Ripristina TUTTO"},
                {"rp.restore.all.tt", "Ripristina tutti i file"},
                {"rp.restore.done", "Ripristino completato. File ripristinati: {0}"},
                {"rp.restore.copy.done", "File copiati: {0}\nDestinazione: {1}"},
                {"rp.restore.incomplete", "Backup in corso o non completato."},
                {"rp.restore.notfound", "Versione #{0} non trovata."},
                {"rp.restore.prepare.fail", "Preparazione dello snapshot per la versione {0} fallita:\n{1}"},
                {"rp.restore.prepareVersion.fail", "Preparazione dei dati della versione fallita:\n{0}"},
                {"rp.restore.selected", "Ripristina selezionati"},
                {"rp.restore.selected.tt", "Ripristina i file selezionati"},
                {"rp.restore.copy", "Ripristina come copia"},
                {"rp.restore.copy.tt", "Copia i file selezionati in un'altra cartella"},
                {"rp.restore.title", "Ripristina"},
                {"rp.safety", "Backup di sicurezza"},
                {"rp.safety.tt", "Crea una copia PreRestore prima del ripristino"},
                {"rp.scan.bar", "Analisi differenze"},
                {"rp.scan.progress", "Scansione dei file... {0}/{1} ({2:0.0}%)"},
                {"rp.search", "Cerca:"},
                {"rp.select.all", "Seleziona tutto"},
                {"rp.select.newchanged", "Seleziona nuovi+modificati"},
                {"rp.selected.summary", "Selezionati: {0} file ({1})"},
                {"rp.stat.changed", "MODIFICATI"},
                {"rp.stat.new", "NUOVI"},
                {"rp.stat.same", "UGUALI"},
                {"rp.stats", "File: {0}   Nuovi: {1}   Modificati: {2}   Uguali: {3}"},
                {"rp.title", "Anteprima ripristino"},
                {"rp.top.extensions", "Estensioni principali"},
                {"rp.version.notfound", "File della versione non trovati."},
                {"rp.yes", "SÃ¬"},
                {"tt.advanced.openLogFolder", "Apri la cartella dei log per il supporto"},
                {"tt.advanced.refreshVersions", "Ricarica l'elenco delle versioni"},
                {"tt.backup.now.advanced", "Esegui subito un backup (nessun cooldown in ModalitÃ  avanzata)"},
                {"tt.latest.none", "Nessuna versione disponibile"},
                {"tt.latest.open", "Apri l'ultima versione per ripristinare o ispezionare"},
                {"tt.open.backup.folder", "Apri la cartella dei backup"},
                {"tt.overview.gotoVersions", "Apri la scheda Versioni"},
                {"tt.versions.refresh", "Ricarica le versioni dal disco"},
                {"ui.advanced.openLogFolder", "Apri cartella log"},
                {"ui.advanced.refreshVersions", "Aggiorna versioni"},
                {"ui.advanced.tools.title", "Strumenti avanzati"},
                {"ui.advancedMode", "ModalitÃ  avanzata"},
                {"ui.advancedMode.tooltip", "Mostra le opzioni avanzate (filtri, prestazioni, verifica, retention)."},
                {"ui.autobackups.last", "Ultimo"},
                {"ui.autobackups.next", "Successivo"},
                {"ui.autobackups.off", "Backup automatici: OFF"},
                {"ui.autobackups.on", "Backup automatici: ON"},
                {"ui.autobackups.title", "Backup automatici"},
                {"ui.filters.pending", "Modifiche ai filtri in attesa. Il prossimo backup creerà un checkpoint completo per applicare il nuovo scope."},
                {"ui.mode.label", "Modalità"},
                {"ui.mode.easy", "Semplice"},
                {"ui.mode.advanced", "Avanzata"},
                {"ui.easy.summary", "La modalità Semplice mostra solo l'essenziale. Passa ad Avanzata per i controlli dettagliati."},
                                {"ui.easy.switch", "Passa ad Avanzata"},
                {"onboarding.title", "Benvenuto in Avatar Smart Backup"},
                {"onboarding.body", "Scegli l'esperienza che preferisci. Potrai cambiarla in seguito dal selettore modalità."},
                {"onboarding.learn", "Scopri di più"},
                {"onboarding.learn.body", "La modalità Semplice mostra solo l'essenziale. La modalità Avanzata espone tutti gli strumenti."},
                {"ui.autobackups.toggle.tt", "Attiva/disattiva la pianificazione dei backup in background"},
                {"ui.backup.now", "Backup ora"},
                {"ui.interval.label", "Intervallo"},
                {"ui.interval.min", "min"},
                {"ui.interval.sec", "sec"},
                {"ui.latest.previewRestore", "Anteprima e ripristino dell'ultima"},
                {"ui.never", "mai"},
                {"ui.open.backup.folder", "Apri cartella backup"},
                {"ui.overview.created", "Creato:"},
                {"ui.overview.filesSize", "File"},
                {"ui.overview.gotoVersions", "Vai alle versioni"},
                {"ui.overview.latest.label", "Ultima versione:"},
                {"ui.overview.latest.title", "Ultima versione"},
                {"ui.overview.noDescription", "(nessuna descrizione)"},
                {"ui.overview.none", "Nessuna versione disponibile"},
                {"ui.overview.size", "Dimensione"},
                {"ui.tabs.backup", "Backup"},
                {"ui.tabs.versions", "Versioni"},
                {"ui.versions.help", "I punti di ripristino vengono creati automaticamente quando ci sono modifiche. Usa la stella per fissare, clicca per selezionare, doppio clic per l'anteprima."},
                {"ui.versions.refresh", "Aggiorna"},
                {"ui.versions.previewRestore", "Anteprima e ripristino"},
                {"ui.versions.title", "Versioni"},
                {"vh.created", "Creato:"},
                {"vh.desc", "Descrizione: {0}"},
                {"vh.folder.notfound.body", "Impossibile trovare la cartella della versione."},
                {"vh.folder.notfound.title", "Cartella non trovata"},
                {"vh.latest", "Ultima"},
                {"vh.load.error", "Errore durante il caricamento delle versioni: {0}"},
                {"vh.loading", "Caricamento delle versioni..."},
                {"vh.none", "Nessuna versione trovata. Le versioni vengono create automaticamente dopo ogni backup con modifiche."},
                {"vh.open.folder", "Apri cartella"},
                {"vh.show.changes", "Mostra modifiche"},
                {"vh.refresh", "Aggiorna"},
                {"vh.restore", "Ripristina a questa versione"},
                {"vh.restore.confirm.body", "Sei sicuro di voler ripristinare alla versione #{0}?\n\nDescrizione: {1}\nCreato: {2}\n\nQuesto sostituirÃ  gli Assets attuali con il backup di questa versione."},
                {"vh.restore.confirm.cancel", "Annulla"},
                {"vh.restore.confirm.ok", "Ripristina"},
                {"vh.restore.confirm.title", "Conferma ripristino"},
                {"vh.restore.failed.body", "Ripristino della versione fallito: {0}"},
                {"vh.restore.failed.title", "Ripristino fallito"},
                {"vh.restore.location.body", "I file di backup della versione #{0} si trovano in:\n\n{1}\n\nPuoi copiarli manualmente nella cartella Assets se necessario."},
                {"vh.restore.location.title", "Percorso di ripristino"},
                {"vh.restore.notfound.body", "Impossibile trovare la cartella di backup per la versione #{0} in:\n\n{1}"},
                {"vh.restore.notfound.title", "Backup non trovato"},
                {"vh.tip.cleanup", "Suggerimento: le versioni vengono pulite automaticamente mantenendo solo le 10 piÃ¹ recenti."},
                {"vh.title", "Versioni di backup"},
                {"vh.total", "Versioni totali: {0}"},
                {"vh.version.header", "Versione #{0}"},
                {"vc.window.title", "Modifiche per v{0}"},
                {"vc.error.title", "Mostra modifiche"},
                {"vc.error.body", "Impossibile leggere le modifiche:\n{0}"},
                {"vc.error.noversion", "Impossibile aprire la finestra delle modifiche: dati versione assenti."},
                {"vc.no.version", "Nessuna informazione sulla versione disponibile."},
                {"vc.version.header", "Versione #{0}"},
                {"vc.summary.checkpoint", "Checkpoint completo (istantanea completa)."},
                {"vc.summary.incremental", "Versione incrementale (basata sul checkpoint #{0})."},
                {"vc.summary.changed", "Modificati: {0}"},
                {"vc.summary.removed", "Rimossi: {0}"},
                {"vc.summary.bytes.changed", "Delta: {0}"},
                {"vc.summary.bytes.removed", "Byte rimossi: {0}"},
                {"vc.filter.search", "Cerca"},
                {"vc.filter.added", "Nuovi"},
                {"vc.filter.modified", "Modificati"},
                {"vc.filter.removed", "Rimossi"},
                {"vc.filter.clear", "Pulisci"},
                {"vc.filter.namesonly", "Solo nome file"},
                {"vc.filter.highlight", "Evidenzia risultati"},
                {"vc.none", "Nessuna modifica registrata per questa versione."},
                {"vc.none.filters", "I filtri nascondono tutte le voci. Modifica le opzioni o la ricerca."},
                {"vc.kind.added", "Aggiunto"},
                {"vc.kind.modified", "Modificato"},
                {"vc.kind.removed", "Rimosso"},
                {"vc.badge.checkpoint", "Checkpoint"},
                {"vc.badge.incremental", "Incrementale"},
                {"warn.backup.speed", "A {0} MB/s, il backup di {1:0.0} MB richiede ~{2:0.0} min, superando l'intervallo."},
                {"window.main.autobackup.help", "Le copie di sicurezza automatiche vengono eseguite in background. Usa \"Backup ora\" per forzarne una (con limitazione)."},
                {"window.main.header", "Avatar Smart Backup"},
                {"window.main.title", "Avatar Smart Backup"},
                {"window.version.history.help", "Le versioni sono di due tipi: checkpoint completi e incrementali. Le versioni incrementali contengono solo le modifiche rispetto al checkpoint precedente."},
            {"ui.advanced.settings", "Impostazioni avanzate"},
            {"ui.versioning.policy.title", "Politica versioning"},
            {"ui.versioning.policy.option.balanced", "Automatica"},
            {"ui.versioning.policy.option.frequent", "Frequente"},
            {"ui.versioning.policy.option.manual", "Manuale"},
            {"ui.versioning.policy.mode", "Preset"},
            {"ui.versioning.policy.mode.tooltip", "Scegli con quale frequenza forzare i checkpoint."},
            {"ui.versioning.policy.balanced.help", "Checkpoint automatici basati sull'attività del progetto."},
            {"ui.versioning.policy.frequent.help", "Favorisce checkpoint frequenti dopo modifiche importanti."},
            {"ui.versioning.policy.manual.label", "Checkpoint ogni (versioni incrementali)"},
            {"ui.versioning.policy.manual.tooltip", "Numero di versioni incrementali prima di forzare un checkpoint completo."},
            {"ui.versioning.policy.manual.help", "Forza un checkpoint completo dopo {0} versioni incrementali."},
            {"ui.performance.title", "Prestazioni"},
            {"ui.performance.autoThrottle", "Auto throttle (consigliato)"},
            {"ui.performance.autoThrottle.tt", "Limita automaticamente il throughput disco per mantenere l'editor reattivo."},
            {"ui.performance.threads", "Thread paralleli max"},
            {"ui.performance.threads.tt", "Thread concorrenti per hashing e copia."},
            {"ui.performance.saveScenes", "Salva le scene aperte prima del backup"},
            {"ui.performance.saveScenes.tt", "Salva le scene sporche prima di eseguire il backup."},
            {"ui.performance.autothrottle.off", "Auto throttle disattivato. Verranno usati i limiti manuali se impostati."},
            {"ui.debug.tools.title", "Strumenti debug"},
            {"ui.debug.tools.enable", "Abilita strumenti debug"},
            {"ui.debug.tools.enable.tt", "Attiva diagnostica, logging e override manuali."},
            {"ui.debug.tools.global", "Usa impostazioni globali"},
            {"ui.debug.tools.global.tt", "Condividi questa configurazione tra i progetti."},
            {"ui.debug.tools.throughput", "Throughput misurato: {0:0.0} MB/s"},
            {"ui.debug.tools.throughput.none", "Il benchmark non è ancora stato eseguito."},
            {"ui.debug.tools.benchmark", "Esegui benchmark"},
            {"ui.debug.tools.benchmark.busy", "Benchmark non disponibile durante un backup in corso."},
            {"ui.debug.tools.cooldowns", "Cooldown manuali"},
            {"ui.debug.tools.snapshot.cooldown", "Cooldown snapshot (s)"},
            {"ui.debug.tools.snapshot.cooldown.tt", "Secondi minimi tra snapshot manuali."},
            {"ui.debug.tools.benchmark.cooldown", "Cooldown benchmark (s)"},
            {"ui.debug.tools.benchmark.cooldown.tt", "Secondi minimi tra benchmark manuali."},
            {"ui.debug.tools.backup.cooldown", "Intervallo minimo backup (s)"},
            {"ui.debug.tools.backup.cooldown.tt", "Secondi minimi tra backup manuali."},
            {"ui.debug.tools.logs", "Log dettagliati file"},
            {"ui.debug.tools.logs.tt", "Scrive log dettagliati dei file per il troubleshooting."},
            {"ui.debug.tools.snapshots.info", "Gli snapshot zip ora sono gestiti automaticamente. Le impostazioni legacy restano disponibili per compatibilità."},
            {"ui.debug.tools.disabled", "Abilita per accedere a diagnostica e override manuali."},
            {"ui.versions.latestBadge", "Ultima"},
            {"ui.versions.status.writing", "(scrittura in corso)"},
            };

            L.AddSource(new DictionaryLocalizationSource(en, it));
        }
    }
}
#endif
